#!/bin/bash

####################
# SBATCH OPTIONS
####################
#SBATCH --job-name=bootEx              # job name for queue, default may be u$
#SBATCH --partition=low                # high/low/gpu, default if empty is low
#SBATCH --error=boot.err               # error file, default if empty is slurm$
#SBATCH --time=00:10:00                # hours:minutes:seconds
#SBATCH --nodes=1                      # only use 1 node, MPI option
#SBATCH --ntasks=1                     # how many tasks to start
#SBATCH --cpus-per-task=3              # number of cores to use, multi-core/mu$

####################
# What to run
####################

R CMD BATCH --no-save boot.R boot.Rout


